#!/usr/bin/env python3
"""Regenerate the 'More repos' column table in the profile README.

Rules (per request):
- Max 10 repos per column, add columns as repo count grows, max 4 columns (40 shown).
- Anything past 40 gets a redirect link to the repos tab.
- Each cell: repo title hyperlink in <h2>, description in <h3>.
- Keeps the <details> collapsible wrapper; only replaces content between
  <!-- MORE-REPOS:START --> and <!-- MORE-REPOS:END -->.

Usage:
    python3 scripts/update-more-repos.py [--check] [--readme PATH]

- Default README path: <repo-root>/README.md
- --check: exit 1 if README would change (for CI dry-run).
- Uses `gh` CLI (authenticated) to list repos; falls back to `gh api`.
"""

from __future__ import annotations

import argparse
import html
import json
import subprocess
import sys
from pathlib import Path

OWNER = "needlehmbl"
REPOS_TAB = f"https://github.com/{OWNER}?tab=repositories"

# Featured table entries — never duplicated into "More repos".
FEATURED = {
    "3d-portfolio",
    "job-scraper",
    "local-rag",
    "media-manager",
    "doc-pipeline",
    "kanban",
}

# Never listed (profile README repo itself).
EXCLUDE = {"needlehmbl"}

# Fallbacks for repos with an empty GitHub description.
# If the API description is non-empty it always wins; these only fill gaps
# so future auto-added repos still get a one-liner until you set a description.
FALLBACK_DESCRIPTIONS = {
    "glowpoint-dashboard": "TypeScript dashboard",
    "glowpoint-client": "JavaScript client",
    "nasa-react-app": "NASA API React app",
    "go-go-ghost": "Godot / GDScript game",
    "TPWeb": "Web tech project (CSS)",
}

PER_COLUMN = 10
MAX_COLUMNS = 4
MAX_SHOWN = PER_COLUMN * MAX_COLUMNS

START_MARKER = "<!-- MORE-REPOS:START -->"
END_MARKER = "<!-- MORE-REPOS:END -->"


def fetch_repos() -> list[dict]:
    out = subprocess.run(
        [
            "gh",
            "repo",
            "list",
            OWNER,
            "--limit",
            "200",
            "--json",
            "name,description,url,isFork,isPrivate,isArchived",
        ],
        capture_output=True,
        text=True,
        check=True,
    )
    return json.loads(out.stdout or "[]")


def pick_repos(all_repos: list[dict]) -> list[dict]:
    picked = []
    for r in all_repos:
        name = r.get("name", "")
        if name in FEATURED or name in EXCLUDE:
            continue
        if r.get("isPrivate") or r.get("isFork") or r.get("isArchived"):
            continue
        desc = (r.get("description") or "").strip() or FALLBACK_DESCRIPTIONS.get(name, "No description yet.")
        picked.append({"name": name, "url": r.get("url") or f"https://github.com/{OWNER}/{name}", "description": desc})
    picked.sort(key=lambda r: r["name"].lower())
    return picked


def repo_block(repo: dict) -> str:
    name = html.escape(repo["name"])
    url = html.escape(repo["url"], quote=True)
    desc = html.escape(repo["description"])
    return f"<h2><a href=\"{url}\">{name}</a></h2>\n<h3>{desc}</h3>"


def build_table(repos: list[dict]) -> str:
    shown = repos[:MAX_SHOWN]
    overflow = len(repos) - len(shown)
    # Chunk into columns of PER_COLUMN.
    columns = [shown[i : i + PER_COLUMN] for i in range(0, len(shown), PER_COLUMN)] or [[]]

    lines = [START_MARKER]
    lines.append("<!-- Auto-generated by scripts/update-more-repos.py — do not edit manually. Columns: max 10 repos each, up to 4 columns (40 repos max). Overflow links to the repos tab. -->")
    lines.append("<table>")
    lines.append("<tr>")
    for col in columns:
        lines.append('<td valign="top">')
        lines.append("")
        for i, repo in enumerate(col):
            lines.append(repo_block(repo))
            if i < len(col) - 1:
                lines.append("<br/>")
                lines.append("")
        lines.append("")
        lines.append("</td>")
    lines.append("</tr>")
    lines.append("</table>")
    if overflow > 0:
        lines.append("")
        lines.append(f'<p align="center">➡️ Showing {MAX_SHOWN} of {len(repos)} repos — <a href="{REPOS_TAB}">See all repositories</a></p>')
    lines.append(END_MARKER)
    return "\n".join(lines) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="Exit 1 if README would change.")
    ap.add_argument("--readme", default=None, help="Path to README.md (default: repo-root/README.md).")
    args = ap.parse_args()

    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent
    readme = Path(args.readme) if args.readme else repo_root / "README.md"

    repos = pick_repos(fetch_repos())
    new_block = build_table(repos)

    text = readme.read_text(encoding="utf-8")
    if START_MARKER not in text or END_MARKER not in text:
        print(f"Markers not found in {readme}", file=sys.stderr)
        return 2
    before, _, rest = text.partition(START_MARKER)
    _, _, after = rest.partition(END_MARKER)
    # Normalize surrounding blank lines so repeated runs are idempotent.
    updated = before + new_block + "\n" + after.lstrip("\n")

    if updated == text:
        print(f"No change ({len(repos)} more repos).")
        return 0
    if args.check:
        print(f"Would update: {len(repos)} more repos.")
        return 1
    readme.write_text(updated, encoding="utf-8")
    print(f"Updated {readme}: {len(repos)} more repos, {min(len(repos), MAX_SHOWN)} shown.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
